// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Chaika-Team/ChaikaGoods/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddTemplate provides a mock function with given fields: ctx, template
func (_m *MockService) AddTemplate(ctx context.Context, template *models.Template) (int64, error) {
	ret := _m.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for AddTemplate")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Template) (int64, error)); ok {
		return rf(ctx, template)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Template) int64); ok {
		r0 = rf(ctx, template)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Template) error); ok {
		r1 = rf(ctx, template)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_AddTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTemplate'
type MockService_AddTemplate_Call struct {
	*mock.Call
}

// AddTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - template *models.Template
func (_e *MockService_Expecter) AddTemplate(ctx interface{}, template interface{}) *MockService_AddTemplate_Call {
	return &MockService_AddTemplate_Call{Call: _e.mock.On("AddTemplate", ctx, template)}
}

func (_c *MockService_AddTemplate_Call) Run(run func(ctx context.Context, template *models.Template)) *MockService_AddTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Template))
	})
	return _c
}

func (_c *MockService_AddTemplate_Call) Return(_a0 int64, _a1 error) *MockService_AddTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_AddTemplate_Call) RunAndReturn(run func(context.Context, *models.Template) (int64, error)) *MockService_AddTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function with given fields: ctx, p
func (_m *MockService) CreateProduct(ctx context.Context, p *models.Product) (int64, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Product) (int64, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Product) int64); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Product) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockService_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - p *models.Product
func (_e *MockService_Expecter) CreateProduct(ctx interface{}, p interface{}) *MockService_CreateProduct_Call {
	return &MockService_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, p)}
}

func (_c *MockService_CreateProduct_Call) Run(run func(ctx context.Context, p *models.Product)) *MockService_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Product))
	})
	return _c
}

func (_c *MockService_CreateProduct_Call) Return(_a0 int64, _a1 error) *MockService_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateProduct_Call) RunAndReturn(run func(context.Context, *models.Product) (int64, error)) *MockService_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteProduct(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockService_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) DeleteProduct(ctx interface{}, id interface{}) *MockService_DeleteProduct_Call {
	return &MockService_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *MockService_DeleteProduct_Call) Run(run func(ctx context.Context, id int64)) *MockService_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_DeleteProduct_Call) Return(_a0 error) *MockService_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteProduct_Call) RunAndReturn(run func(context.Context, int64) error) *MockService_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllProducts provides a mock function with given fields: ctx
func (_m *MockService) GetAllProducts(ctx context.Context) ([]models.Product, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Product, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProducts'
type MockService_GetAllProducts_Call struct {
	*mock.Call
}

// GetAllProducts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetAllProducts(ctx interface{}) *MockService_GetAllProducts_Call {
	return &MockService_GetAllProducts_Call{Call: _e.mock.On("GetAllProducts", ctx)}
}

func (_c *MockService_GetAllProducts_Call) Run(run func(ctx context.Context)) *MockService_GetAllProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetAllProducts_Call) Return(_a0 []models.Product, _a1 error) *MockService_GetAllProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllProducts_Call) RunAndReturn(run func(context.Context) ([]models.Product, error)) *MockService_GetAllProducts_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *MockService) GetProductByID(ctx context.Context, id int64) (models.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockService_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) GetProductByID(ctx interface{}, id interface{}) *MockService_GetProductByID_Call {
	return &MockService_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *MockService_GetProductByID_Call) Run(run func(ctx context.Context, id int64)) *MockService_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_GetProductByID_Call) Return(_a0 models.Product, _a1 error) *MockService_GetProductByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetProductByID_Call) RunAndReturn(run func(context.Context, int64) (models.Product, error)) *MockService_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplateByID provides a mock function with given fields: ctx, id
func (_m *MockService) GetTemplateByID(ctx context.Context, id int64) (models.Template, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByID")
	}

	var r0 models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Template, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Template); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetTemplateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateByID'
type MockService_GetTemplateByID_Call struct {
	*mock.Call
}

// GetTemplateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) GetTemplateByID(ctx interface{}, id interface{}) *MockService_GetTemplateByID_Call {
	return &MockService_GetTemplateByID_Call{Call: _e.mock.On("GetTemplateByID", ctx, id)}
}

func (_c *MockService_GetTemplateByID_Call) Run(run func(ctx context.Context, id int64)) *MockService_GetTemplateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_GetTemplateByID_Call) Return(_a0 models.Template, _a1 error) *MockService_GetTemplateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetTemplateByID_Call) RunAndReturn(run func(context.Context, int64) (models.Template, error)) *MockService_GetTemplateByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTemplates provides a mock function with given fields: ctx, searchString, limit, offset
func (_m *MockService) SearchTemplates(ctx context.Context, searchString string, limit int64, offset int64) ([]models.Template, error) {
	ret := _m.Called(ctx, searchString, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchTemplates")
	}

	var r0 []models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]models.Template, error)); ok {
		return rf(ctx, searchString, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []models.Template); ok {
		r0 = rf(ctx, searchString, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, searchString, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SearchTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTemplates'
type MockService_SearchTemplates_Call struct {
	*mock.Call
}

// SearchTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - searchString string
//   - limit int64
//   - offset int64
func (_e *MockService_Expecter) SearchTemplates(ctx interface{}, searchString interface{}, limit interface{}, offset interface{}) *MockService_SearchTemplates_Call {
	return &MockService_SearchTemplates_Call{Call: _e.mock.On("SearchTemplates", ctx, searchString, limit, offset)}
}

func (_c *MockService_SearchTemplates_Call) Run(run func(ctx context.Context, searchString string, limit int64, offset int64)) *MockService_SearchTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockService_SearchTemplates_Call) Return(_a0 []models.Template, _a1 error) *MockService_SearchTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_SearchTemplates_Call) RunAndReturn(run func(context.Context, string, int64, int64) ([]models.Template, error)) *MockService_SearchTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: ctx, p
func (_m *MockService) UpdateProduct(ctx context.Context, p *models.Product) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Product) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockService_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - p *models.Product
func (_e *MockService_Expecter) UpdateProduct(ctx interface{}, p interface{}) *MockService_UpdateProduct_Call {
	return &MockService_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, p)}
}

func (_c *MockService_UpdateProduct_Call) Run(run func(ctx context.Context, p *models.Product)) *MockService_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Product))
	})
	return _c
}

func (_c *MockService_UpdateProduct_Call) Return(_a0 error) *MockService_UpdateProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateProduct_Call) RunAndReturn(run func(context.Context, *models.Product) error) *MockService_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
