// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Chaika-Team/ChaikaGoods/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockTemplateRepository is an autogenerated mock type for the TemplateRepository type
type MockTemplateRepository struct {
	mock.Mock
}

type MockTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRepository) EXPECT() *MockTemplateRepository_Expecter {
	return &MockTemplateRepository_Expecter{mock: &_m.Mock}
}

// CreateTemplate provides a mock function with given fields: ctx, template
func (_m *MockTemplateRepository) CreateTemplate(ctx context.Context, template *models.Template) error {
	ret := _m.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Template) error); ok {
		r0 = rf(ctx, template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_CreateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemplate'
type MockTemplateRepository_CreateTemplate_Call struct {
	*mock.Call
}

// CreateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - template *models.Template
func (_e *MockTemplateRepository_Expecter) CreateTemplate(ctx interface{}, template interface{}) *MockTemplateRepository_CreateTemplate_Call {
	return &MockTemplateRepository_CreateTemplate_Call{Call: _e.mock.On("CreateTemplate", ctx, template)}
}

func (_c *MockTemplateRepository_CreateTemplate_Call) Run(run func(ctx context.Context, template *models.Template)) *MockTemplateRepository_CreateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Template))
	})
	return _c
}

func (_c *MockTemplateRepository_CreateTemplate_Call) Return(_a0 error) *MockTemplateRepository_CreateTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_CreateTemplate_Call) RunAndReturn(run func(context.Context, *models.Template) error) *MockTemplateRepository_CreateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTemplate provides a mock function with given fields: ctx, templateID
func (_m *MockTemplateRepository) DeleteTemplate(ctx context.Context, templateID int64) error {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, templateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_DeleteTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTemplate'
type MockTemplateRepository_DeleteTemplate_Call struct {
	*mock.Call
}

// DeleteTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID int64
func (_e *MockTemplateRepository_Expecter) DeleteTemplate(ctx interface{}, templateID interface{}) *MockTemplateRepository_DeleteTemplate_Call {
	return &MockTemplateRepository_DeleteTemplate_Call{Call: _e.mock.On("DeleteTemplate", ctx, templateID)}
}

func (_c *MockTemplateRepository_DeleteTemplate_Call) Run(run func(ctx context.Context, templateID int64)) *MockTemplateRepository_DeleteTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTemplateRepository_DeleteTemplate_Call) Return(_a0 error) *MockTemplateRepository_DeleteTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_DeleteTemplate_Call) RunAndReturn(run func(context.Context, int64) error) *MockTemplateRepository_DeleteTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTemplates provides a mock function with given fields: ctx, limit, offset
func (_m *MockTemplateRepository) GetAllTemplates(ctx context.Context, limit int64, offset int64) ([]models.Template, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTemplates")
	}

	var r0 []models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]models.Template, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []models.Template); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_GetAllTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTemplates'
type MockTemplateRepository_GetAllTemplates_Call struct {
	*mock.Call
}

// GetAllTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
//   - offset int64
func (_e *MockTemplateRepository_Expecter) GetAllTemplates(ctx interface{}, limit interface{}, offset interface{}) *MockTemplateRepository_GetAllTemplates_Call {
	return &MockTemplateRepository_GetAllTemplates_Call{Call: _e.mock.On("GetAllTemplates", ctx, limit, offset)}
}

func (_c *MockTemplateRepository_GetAllTemplates_Call) Run(run func(ctx context.Context, limit int64, offset int64)) *MockTemplateRepository_GetAllTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockTemplateRepository_GetAllTemplates_Call) Return(_a0 []models.Template, _a1 error) *MockTemplateRepository_GetAllTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_GetAllTemplates_Call) RunAndReturn(run func(context.Context, int64, int64) ([]models.Template, error)) *MockTemplateRepository_GetAllTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductsByTemplateID provides a mock function with given fields: ctx, templateID
func (_m *MockTemplateRepository) GetProductsByTemplateID(ctx context.Context, templateID int64) ([]models.TemplateContent, error) {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByTemplateID")
	}

	var r0 []models.TemplateContent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.TemplateContent, error)); ok {
		return rf(ctx, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.TemplateContent); ok {
		r0 = rf(ctx, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TemplateContent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_GetProductsByTemplateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductsByTemplateID'
type MockTemplateRepository_GetProductsByTemplateID_Call struct {
	*mock.Call
}

// GetProductsByTemplateID is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID int64
func (_e *MockTemplateRepository_Expecter) GetProductsByTemplateID(ctx interface{}, templateID interface{}) *MockTemplateRepository_GetProductsByTemplateID_Call {
	return &MockTemplateRepository_GetProductsByTemplateID_Call{Call: _e.mock.On("GetProductsByTemplateID", ctx, templateID)}
}

func (_c *MockTemplateRepository_GetProductsByTemplateID_Call) Run(run func(ctx context.Context, templateID int64)) *MockTemplateRepository_GetProductsByTemplateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTemplateRepository_GetProductsByTemplateID_Call) Return(_a0 []models.TemplateContent, _a1 error) *MockTemplateRepository_GetProductsByTemplateID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_GetProductsByTemplateID_Call) RunAndReturn(run func(context.Context, int64) ([]models.TemplateContent, error)) *MockTemplateRepository_GetProductsByTemplateID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplateByID provides a mock function with given fields: ctx, id
func (_m *MockTemplateRepository) GetTemplateByID(ctx context.Context, id int64) (models.Template, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByID")
	}

	var r0 models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Template, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Template); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_GetTemplateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateByID'
type MockTemplateRepository_GetTemplateByID_Call struct {
	*mock.Call
}

// GetTemplateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTemplateRepository_Expecter) GetTemplateByID(ctx interface{}, id interface{}) *MockTemplateRepository_GetTemplateByID_Call {
	return &MockTemplateRepository_GetTemplateByID_Call{Call: _e.mock.On("GetTemplateByID", ctx, id)}
}

func (_c *MockTemplateRepository_GetTemplateByID_Call) Run(run func(ctx context.Context, id int64)) *MockTemplateRepository_GetTemplateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTemplateRepository_GetTemplateByID_Call) Return(_a0 models.Template, _a1 error) *MockTemplateRepository_GetTemplateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_GetTemplateByID_Call) RunAndReturn(run func(context.Context, int64) (models.Template, error)) *MockTemplateRepository_GetTemplateByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListTemplates provides a mock function with given fields: ctx
func (_m *MockTemplateRepository) ListTemplates(ctx context.Context) ([]models.Template, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTemplates")
	}

	var r0 []models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Template, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Template); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_ListTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTemplates'
type MockTemplateRepository_ListTemplates_Call struct {
	*mock.Call
}

// ListTemplates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTemplateRepository_Expecter) ListTemplates(ctx interface{}) *MockTemplateRepository_ListTemplates_Call {
	return &MockTemplateRepository_ListTemplates_Call{Call: _e.mock.On("ListTemplates", ctx)}
}

func (_c *MockTemplateRepository_ListTemplates_Call) Run(run func(ctx context.Context)) *MockTemplateRepository_ListTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTemplateRepository_ListTemplates_Call) Return(_a0 []models.Template, _a1 error) *MockTemplateRepository_ListTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_ListTemplates_Call) RunAndReturn(run func(context.Context) ([]models.Template, error)) *MockTemplateRepository_ListTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTemplates provides a mock function with given fields: ctx, searchString, limit, offset
func (_m *MockTemplateRepository) SearchTemplates(ctx context.Context, searchString string, limit int64, offset int64) ([]models.Template, error) {
	ret := _m.Called(ctx, searchString, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchTemplates")
	}

	var r0 []models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]models.Template, error)); ok {
		return rf(ctx, searchString, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []models.Template); ok {
		r0 = rf(ctx, searchString, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, searchString, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_SearchTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTemplates'
type MockTemplateRepository_SearchTemplates_Call struct {
	*mock.Call
}

// SearchTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - searchString string
//   - limit int64
//   - offset int64
func (_e *MockTemplateRepository_Expecter) SearchTemplates(ctx interface{}, searchString interface{}, limit interface{}, offset interface{}) *MockTemplateRepository_SearchTemplates_Call {
	return &MockTemplateRepository_SearchTemplates_Call{Call: _e.mock.On("SearchTemplates", ctx, searchString, limit, offset)}
}

func (_c *MockTemplateRepository_SearchTemplates_Call) Run(run func(ctx context.Context, searchString string, limit int64, offset int64)) *MockTemplateRepository_SearchTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockTemplateRepository_SearchTemplates_Call) Return(_a0 []models.Template, _a1 error) *MockTemplateRepository_SearchTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_SearchTemplates_Call) RunAndReturn(run func(context.Context, string, int64, int64) ([]models.Template, error)) *MockTemplateRepository_SearchTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateRepository creates a new instance of MockTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRepository {
	mock := &MockTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
