with-expecter: true
issue-845-fix: true
resolve-type-alias: false

packages:
  github.com/Chaika-Team/ChaikaGoods/internal/models:
    config:
      mockname: "Mock{{.InterfaceName}}"
      filename: "{{.InterfaceName}}.mock.go"
      dir: "tests/mocks"
      outpkg: "mocks"
      inpackage: false
    interfaces:
      GoodsRepository:
