// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Chaika-Team/ChaikaGoods/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockGoodsRepository is an autogenerated mock type for the GoodsRepository type
type MockGoodsRepository struct {
	mock.Mock
}

type MockGoodsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoodsRepository) EXPECT() *MockGoodsRepository_Expecter {
	return &MockGoodsRepository_Expecter{mock: &_m.Mock}
}

// CreatePackage provides a mock function with given fields: ctx, pkg
func (_m *MockGoodsRepository) CreatePackage(ctx context.Context, pkg *models.Package) error {
	ret := _m.Called(ctx, pkg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePackage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Package) error); ok {
		r0 = rf(ctx, pkg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoodsRepository_CreatePackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePackage'
type MockGoodsRepository_CreatePackage_Call struct {
	*mock.Call
}

// CreatePackage is a helper method to define mock.On call
//   - ctx context.Context
//   - pkg *models.Package
func (_e *MockGoodsRepository_Expecter) CreatePackage(ctx interface{}, pkg interface{}) *MockGoodsRepository_CreatePackage_Call {
	return &MockGoodsRepository_CreatePackage_Call{Call: _e.mock.On("CreatePackage", ctx, pkg)}
}

func (_c *MockGoodsRepository_CreatePackage_Call) Run(run func(ctx context.Context, pkg *models.Package)) *MockGoodsRepository_CreatePackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Package))
	})
	return _c
}

func (_c *MockGoodsRepository_CreatePackage_Call) Return(_a0 error) *MockGoodsRepository_CreatePackage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoodsRepository_CreatePackage_Call) RunAndReturn(run func(context.Context, *models.Package) error) *MockGoodsRepository_CreatePackage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function with given fields: ctx, p
func (_m *MockGoodsRepository) CreateProduct(ctx context.Context, p *models.Product) (int64, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Product) (int64, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Product) int64); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Product) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoodsRepository_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockGoodsRepository_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - p *models.Product
func (_e *MockGoodsRepository_Expecter) CreateProduct(ctx interface{}, p interface{}) *MockGoodsRepository_CreateProduct_Call {
	return &MockGoodsRepository_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, p)}
}

func (_c *MockGoodsRepository_CreateProduct_Call) Run(run func(ctx context.Context, p *models.Product)) *MockGoodsRepository_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Product))
	})
	return _c
}

func (_c *MockGoodsRepository_CreateProduct_Call) Return(_a0 int64, _a1 error) *MockGoodsRepository_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoodsRepository_CreateProduct_Call) RunAndReturn(run func(context.Context, *models.Product) (int64, error)) *MockGoodsRepository_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePackage provides a mock function with given fields: ctx, packageID
func (_m *MockGoodsRepository) DeletePackage(ctx context.Context, packageID int64) error {
	ret := _m.Called(ctx, packageID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePackage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, packageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoodsRepository_DeletePackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePackage'
type MockGoodsRepository_DeletePackage_Call struct {
	*mock.Call
}

// DeletePackage is a helper method to define mock.On call
//   - ctx context.Context
//   - packageID int64
func (_e *MockGoodsRepository_Expecter) DeletePackage(ctx interface{}, packageID interface{}) *MockGoodsRepository_DeletePackage_Call {
	return &MockGoodsRepository_DeletePackage_Call{Call: _e.mock.On("DeletePackage", ctx, packageID)}
}

func (_c *MockGoodsRepository_DeletePackage_Call) Run(run func(ctx context.Context, packageID int64)) *MockGoodsRepository_DeletePackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGoodsRepository_DeletePackage_Call) Return(_a0 error) *MockGoodsRepository_DeletePackage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoodsRepository_DeletePackage_Call) RunAndReturn(run func(context.Context, int64) error) *MockGoodsRepository_DeletePackage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *MockGoodsRepository) DeleteProduct(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoodsRepository_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockGoodsRepository_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockGoodsRepository_Expecter) DeleteProduct(ctx interface{}, id interface{}) *MockGoodsRepository_DeleteProduct_Call {
	return &MockGoodsRepository_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *MockGoodsRepository_DeleteProduct_Call) Run(run func(ctx context.Context, id int64)) *MockGoodsRepository_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGoodsRepository_DeleteProduct_Call) Return(_a0 error) *MockGoodsRepository_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoodsRepository_DeleteProduct_Call) RunAndReturn(run func(context.Context, int64) error) *MockGoodsRepository_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPackages provides a mock function with given fields: ctx, limit, offset
func (_m *MockGoodsRepository) GetAllPackages(ctx context.Context, limit int64, offset int64) ([]models.Package, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPackages")
	}

	var r0 []models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]models.Package, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []models.Package); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoodsRepository_GetAllPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPackages'
type MockGoodsRepository_GetAllPackages_Call struct {
	*mock.Call
}

// GetAllPackages is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
//   - offset int64
func (_e *MockGoodsRepository_Expecter) GetAllPackages(ctx interface{}, limit interface{}, offset interface{}) *MockGoodsRepository_GetAllPackages_Call {
	return &MockGoodsRepository_GetAllPackages_Call{Call: _e.mock.On("GetAllPackages", ctx, limit, offset)}
}

func (_c *MockGoodsRepository_GetAllPackages_Call) Run(run func(ctx context.Context, limit int64, offset int64)) *MockGoodsRepository_GetAllPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockGoodsRepository_GetAllPackages_Call) Return(_a0 []models.Package, _a1 error) *MockGoodsRepository_GetAllPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoodsRepository_GetAllPackages_Call) RunAndReturn(run func(context.Context, int64, int64) ([]models.Package, error)) *MockGoodsRepository_GetAllPackages_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllProducts provides a mock function with given fields: ctx
func (_m *MockGoodsRepository) GetAllProducts(ctx context.Context) ([]models.Product, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Product, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoodsRepository_GetAllProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProducts'
type MockGoodsRepository_GetAllProducts_Call struct {
	*mock.Call
}

// GetAllProducts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGoodsRepository_Expecter) GetAllProducts(ctx interface{}) *MockGoodsRepository_GetAllProducts_Call {
	return &MockGoodsRepository_GetAllProducts_Call{Call: _e.mock.On("GetAllProducts", ctx)}
}

func (_c *MockGoodsRepository_GetAllProducts_Call) Run(run func(ctx context.Context)) *MockGoodsRepository_GetAllProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGoodsRepository_GetAllProducts_Call) Return(_a0 []models.Product, _a1 error) *MockGoodsRepository_GetAllProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoodsRepository_GetAllProducts_Call) RunAndReturn(run func(context.Context) ([]models.Product, error)) *MockGoodsRepository_GetAllProducts_Call {
	_c.Call.Return(run)
	return _c
}

// GetPackageByID provides a mock function with given fields: ctx, id
func (_m *MockGoodsRepository) GetPackageByID(ctx context.Context, id int64) (models.Package, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageByID")
	}

	var r0 models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Package, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Package); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Package)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoodsRepository_GetPackageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackageByID'
type MockGoodsRepository_GetPackageByID_Call struct {
	*mock.Call
}

// GetPackageByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockGoodsRepository_Expecter) GetPackageByID(ctx interface{}, id interface{}) *MockGoodsRepository_GetPackageByID_Call {
	return &MockGoodsRepository_GetPackageByID_Call{Call: _e.mock.On("GetPackageByID", ctx, id)}
}

func (_c *MockGoodsRepository_GetPackageByID_Call) Run(run func(ctx context.Context, id int64)) *MockGoodsRepository_GetPackageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGoodsRepository_GetPackageByID_Call) Return(_a0 models.Package, _a1 error) *MockGoodsRepository_GetPackageByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoodsRepository_GetPackageByID_Call) RunAndReturn(run func(context.Context, int64) (models.Package, error)) *MockGoodsRepository_GetPackageByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *MockGoodsRepository) GetProductByID(ctx context.Context, id int64) (models.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoodsRepository_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockGoodsRepository_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockGoodsRepository_Expecter) GetProductByID(ctx interface{}, id interface{}) *MockGoodsRepository_GetProductByID_Call {
	return &MockGoodsRepository_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *MockGoodsRepository_GetProductByID_Call) Run(run func(ctx context.Context, id int64)) *MockGoodsRepository_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGoodsRepository_GetProductByID_Call) Return(_a0 models.Product, _a1 error) *MockGoodsRepository_GetProductByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoodsRepository_GetProductByID_Call) RunAndReturn(run func(context.Context, int64) (models.Product, error)) *MockGoodsRepository_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductsByPackageID provides a mock function with given fields: ctx, packageID
func (_m *MockGoodsRepository) GetProductsByPackageID(ctx context.Context, packageID int64) ([]models.PackageContent, error) {
	ret := _m.Called(ctx, packageID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByPackageID")
	}

	var r0 []models.PackageContent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.PackageContent, error)); ok {
		return rf(ctx, packageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.PackageContent); ok {
		r0 = rf(ctx, packageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PackageContent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, packageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoodsRepository_GetProductsByPackageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductsByPackageID'
type MockGoodsRepository_GetProductsByPackageID_Call struct {
	*mock.Call
}

// GetProductsByPackageID is a helper method to define mock.On call
//   - ctx context.Context
//   - packageID int64
func (_e *MockGoodsRepository_Expecter) GetProductsByPackageID(ctx interface{}, packageID interface{}) *MockGoodsRepository_GetProductsByPackageID_Call {
	return &MockGoodsRepository_GetProductsByPackageID_Call{Call: _e.mock.On("GetProductsByPackageID", ctx, packageID)}
}

func (_c *MockGoodsRepository_GetProductsByPackageID_Call) Run(run func(ctx context.Context, packageID int64)) *MockGoodsRepository_GetProductsByPackageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGoodsRepository_GetProductsByPackageID_Call) Return(_a0 []models.PackageContent, _a1 error) *MockGoodsRepository_GetProductsByPackageID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoodsRepository_GetProductsByPackageID_Call) RunAndReturn(run func(context.Context, int64) ([]models.PackageContent, error)) *MockGoodsRepository_GetProductsByPackageID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPackages provides a mock function with given fields: ctx
func (_m *MockGoodsRepository) ListPackages(ctx context.Context) ([]models.Package, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPackages")
	}

	var r0 []models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Package, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Package); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoodsRepository_ListPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPackages'
type MockGoodsRepository_ListPackages_Call struct {
	*mock.Call
}

// ListPackages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGoodsRepository_Expecter) ListPackages(ctx interface{}) *MockGoodsRepository_ListPackages_Call {
	return &MockGoodsRepository_ListPackages_Call{Call: _e.mock.On("ListPackages", ctx)}
}

func (_c *MockGoodsRepository_ListPackages_Call) Run(run func(ctx context.Context)) *MockGoodsRepository_ListPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGoodsRepository_ListPackages_Call) Return(_a0 []models.Package, _a1 error) *MockGoodsRepository_ListPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoodsRepository_ListPackages_Call) RunAndReturn(run func(context.Context) ([]models.Package, error)) *MockGoodsRepository_ListPackages_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPackages provides a mock function with given fields: ctx, searchString, limit, offset
func (_m *MockGoodsRepository) SearchPackages(ctx context.Context, searchString string, limit int64, offset int64) ([]models.Package, error) {
	ret := _m.Called(ctx, searchString, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchPackages")
	}

	var r0 []models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]models.Package, error)); ok {
		return rf(ctx, searchString, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []models.Package); ok {
		r0 = rf(ctx, searchString, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, searchString, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoodsRepository_SearchPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPackages'
type MockGoodsRepository_SearchPackages_Call struct {
	*mock.Call
}

// SearchPackages is a helper method to define mock.On call
//   - ctx context.Context
//   - searchString string
//   - limit int64
//   - offset int64
func (_e *MockGoodsRepository_Expecter) SearchPackages(ctx interface{}, searchString interface{}, limit interface{}, offset interface{}) *MockGoodsRepository_SearchPackages_Call {
	return &MockGoodsRepository_SearchPackages_Call{Call: _e.mock.On("SearchPackages", ctx, searchString, limit, offset)}
}

func (_c *MockGoodsRepository_SearchPackages_Call) Run(run func(ctx context.Context, searchString string, limit int64, offset int64)) *MockGoodsRepository_SearchPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockGoodsRepository_SearchPackages_Call) Return(_a0 []models.Package, _a1 error) *MockGoodsRepository_SearchPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoodsRepository_SearchPackages_Call) RunAndReturn(run func(context.Context, string, int64, int64) ([]models.Package, error)) *MockGoodsRepository_SearchPackages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: ctx, p
func (_m *MockGoodsRepository) UpdateProduct(ctx context.Context, p *models.Product) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Product) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoodsRepository_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockGoodsRepository_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - p *models.Product
func (_e *MockGoodsRepository_Expecter) UpdateProduct(ctx interface{}, p interface{}) *MockGoodsRepository_UpdateProduct_Call {
	return &MockGoodsRepository_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, p)}
}

func (_c *MockGoodsRepository_UpdateProduct_Call) Run(run func(ctx context.Context, p *models.Product)) *MockGoodsRepository_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Product))
	})
	return _c
}

func (_c *MockGoodsRepository_UpdateProduct_Call) Return(_a0 error) *MockGoodsRepository_UpdateProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoodsRepository_UpdateProduct_Call) RunAndReturn(run func(context.Context, *models.Product) error) *MockGoodsRepository_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoodsRepository creates a new instance of MockGoodsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoodsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoodsRepository {
	mock := &MockGoodsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
