basePath: /
definitions:
  ChaikaGoods_internal_handler_schemas.AddPacketRequest:
    description: Запрос на добавление пакета
    properties:
      packet:
        allOf:
        - $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.PackageSchema'
        description: Сведения о новом пакете
    type: object
  ChaikaGoods_internal_handler_schemas.AddPacketResponse:
    description: Ответ на запрос на добавление пакета
    properties:
      err:
        type: string
      id:
        description: ID созданного пакета
        type: integer
    type: object
  ChaikaGoods_internal_handler_schemas.AddProductRequest:
    description: Запрос на добавление продукта
    properties:
      product:
        $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ProductSchema'
    type: object
  ChaikaGoods_internal_handler_schemas.AddProductResponse:
    description: Ответ на запрос на добавление продукта
    properties:
      err:
        type: string
      id:
        type: integer
    type: object
  ChaikaGoods_internal_handler_schemas.DeleteProductResponse:
    description: Ответ на запрос на удаление продукта
    properties:
      err:
        type: string
    type: object
  ChaikaGoods_internal_handler_schemas.ErrorResponse:
    description: Represents a standard error response for the API
    properties:
      code:
        description: Error code
        type: integer
      message:
        description: Error message
        type: string
    type: object
  ChaikaGoods_internal_handler_schemas.GetAllProductsResponse:
    description: Ответ на запрос на получение всех продуктов
    properties:
      err:
        type: string
      products:
        items:
          $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ProductSchema'
        type: array
    type: object
  ChaikaGoods_internal_handler_schemas.GetPacketByIDResponse:
    description: Ответ на запрос на получение пакета по его ID
    properties:
      err:
        type: string
      packet:
        $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.PackageSchema'
    type: object
  ChaikaGoods_internal_handler_schemas.GetProductByIDResponse:
    description: Ответ на запрос на получение продукта по его ID
    properties:
      err:
        type: string
      product:
        $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ProductSchema'
    type: object
  ChaikaGoods_internal_handler_schemas.PackageContentSchema:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  ChaikaGoods_internal_handler_schemas.PackageSchema:
    properties:
      content:
        items:
          $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.PackageContentSchema'
        type: array
      description:
        type: string
      id:
        type: integer
      package_name:
        type: string
    type: object
  ChaikaGoods_internal_handler_schemas.ProductSchema:
    properties:
      description:
        type: string
      id:
        type: integer
      imageurl:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  ChaikaGoods_internal_handler_schemas.SearchPacketResponse:
    description: Ответ на запрос на поиск пакетов
    properties:
      err:
        type: string
      packets:
        items:
          $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.PackageSchema'
        type: array
    type: object
  ChaikaGoods_internal_handler_schemas.UpdateProductRequest:
    description: Запрос на обновление продукта
    properties:
      product:
        $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ProductSchema'
    type: object
  ChaikaGoods_internal_handler_schemas.UpdateProductResponse:
    description: Ответ на запрос на обновление продукта
    properties:
      err:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: chaika.contact@yandex.ru
    name: Chaika
  description: This is a simple API to manage goods for the Chaika app.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: ChaikaGoods API
  version: 0.0.2
paths:
  /api/v1/packets:
    post:
      consumes:
      - application/json
      description: Add a new packet of products to the database
      parameters:
      - description: Packet details
        in: body
        name: packet
        required: true
        schema:
          $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.AddPacketRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.AddPacketResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Add packet
      tags:
      - packets
  /api/v1/packets/{id}:
    get:
      consumes:
      - application/json
      description: Get packet details by its ID
      parameters:
      - description: Packet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.GetPacketByIDResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Get packet by ID
      tags:
      - packets
  /api/v1/packets/search:
    get:
      consumes:
      - application/json
      description: Search for packets
      parameters:
      - description: Search query
        in: query
        name: query
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.SearchPacketResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Search packet
      tags:
      - packets
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Get all products from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.GetAllProductsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Add a new product to the database
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.AddProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.AddProductResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Add product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product details in the database
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.UpdateProductResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Update product
      tags:
      - products
  /api/v1/products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product from the database
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.DeleteProductResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Delete product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get product details by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.GetProductByIDResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Get product by ID
      tags:
      - products
produces:
- application/json
schemes:
- http
swagger: "2.0"
