basePath: /
definitions:
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.AddTemplateRequest:
    description: Запрос на добавление шаблона
    properties:
      Template:
        allOf:
        - $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.TemplateSchema'
        description: Сведения о новом шаблоне
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.AddTemplateResponse:
    description: Ответ на запрос на добавление шаблона
    properties:
      id:
        description: ID созданного шаблона
        type: integer
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.CreateProductRequest:
    description: Запрос на добавление продукта
    properties:
      product:
        $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ProductSchema'
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.CreateProductResponse:
    description: Ответ на запрос на добавление продукта
    properties:
      id:
        type: integer
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.DeleteProductResponse:
    description: Ответ на запрос на удаление продукта
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse:
    properties:
      code:
        description: Код ошибки
        type: integer
      message:
        description: Сообщение об ошибке
        type: string
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.GetAllProductsResponse:
    description: Ответ на запрос на получение всех продуктов
    properties:
      products:
        items:
          $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ProductSchema'
        type: array
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.GetProductByIDResponse:
    description: Ответ на запрос на получение продукта по его ID
    properties:
      product:
        $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ProductSchema'
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.GetTemplateByIDResponse:
    description: Ответ на запрос на получение шаблона по его ID
    properties:
      Template:
        $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.TemplateSchema'
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ProductSchema:
    properties:
      description:
        type: string
      id:
        type: integer
      imageurl:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.SearchTemplatesResponse:
    description: Ответ на запрос на поиск шаблонов
    properties:
      Templates:
        items:
          $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.TemplateSchema'
        type: array
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.TemplateContentSchema:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.TemplateSchema:
    properties:
      content:
        items:
          $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.TemplateContentSchema'
        type: array
      description:
        type: string
      id:
        type: integer
      template_name:
        type: string
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.UpdateProductRequest:
    description: Запрос на обновление продукта
    properties:
      product:
        $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ProductSchema'
    type: object
  github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.UpdateProductResponse:
    description: Ответ на запрос на обновление продукта
    type: object
host: chaika-soft.ru
info:
  contact:
    email: chaika.contact@yandex.ru
    name: Chaika
  description: This is a simple API to manage goods for the Chaika app.
  license:
    name: GPL v3
    url: https://www.gnu.de/documents/gpl.en.html
  title: ChaikaGoods API
  version: 1.0.2
paths:
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Get all products from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.GetAllProductsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Add a new product to the database
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.CreateProductResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Add product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product details in the database
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.UpdateProductResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Update product
      tags:
      - products
  /api/v1/products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product from the database
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.DeleteProductResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Delete product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get product details by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.GetProductByIDResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Get product by ID
      tags:
      - products
  /api/v1/templates:
    post:
      consumes:
      - application/json
      description: Add a new Template of products to the database
      parameters:
      - description: Template details
        in: body
        name: Template
        required: true
        schema:
          $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.AddTemplateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.AddTemplateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Add Template
      tags:
      - Templates
  /api/v1/templates/{id}:
    get:
      consumes:
      - application/json
      description: Get Template details by its ID
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.GetTemplateByIDResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Get Template by ID
      tags:
      - Templates
  /api/v1/templates/search:
    get:
      consumes:
      - application/json
      description: Search for Templates
      parameters:
      - description: Search query
        in: query
        name: query
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.SearchTemplatesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Chaika-Team_ChaikaGoods_internal_handler_schemas.ErrorResponse'
      summary: Search Template
      tags:
      - Templates
produces:
- application/json
schemes:
- https
swagger: "2.0"
