# .github/workflows/go-ci.yml

name: Go CI/CD Pipeline

on:
  push:
    branches:
      - master
      - dev
      - ci-cd
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установить нужную версию Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 3. Кэширование модулей Go
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Установка зависимостей
      - name: Install dependencies
        run: go mod download

      # 5. Проверка форматирования кода
      - name: Run go fmt
        run: go fmt ./...

      # 6. Статический анализ кода
      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      # 7. Запуск тестов с покрытием
      - name: Run tests
        run: |
          go test ./... -v -coverprofile=coverage.out -covermode=atomic

      # 8. Сохранение артефактов покрытия
      - name: Upload coverage to artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.out

      # 9. Сборка приложения
      - name: Build
        run: go build -v -o chaika-goods ./cmd

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Checkout код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установить нужную версию Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 3. Run tests and generate coverage
      - name: Run Tests
        run: |
          go test ./... -coverprofile=coverage.out

      # 4. SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=ChaikaGoods
            -Dsonar.sources=./internal,./cmd
            -Dsonar.tests=./internal/tests
            -Dsonar.exclusions=**/tests/**,**/*.mock.go
            -Dsonar.go.coverage.reportPaths=coverage.out
  
